### PR TITLE
Theoretically removing set-output and save-state

### PR DESCRIPTION
**Pull request by rmhrazorhead**

### CODE REVIEW

**Comment by emibcn** [comment]
Hi @rmhrazorhead ,
This repo is mostly done by building another one. I think you can take a look [here](https://github.com/emibcn/github-badge-action/blob/main/src/index.js#L38).

**Comment by rmhrazorhead** [comment]
> Hi @rmhrazorhead , This repo is mostly done by building another one. I think you can take a look [here](https://github.com/emibcn/github-badge-action/blob/main/src/index.js#L38).

This probably won't fix the issues we're seeing then, but it'll at least make it so this repo doesn't use those deprecated calls directly. I'll dig through their open issues and see if they've got any open PRs to fix it on their end.

**Comment by rmhrazorhead** [comment]
Didn't test this locally, so I'd suggest double checking it.

**Comment by emibcn** [comment]
Fixed by fixing the dependency.

Working workflow:
https://github.com/emibcn/github-badge-action/actions/runs/3658127464

**Pull request closed without merging**
